name: Publish & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: GlideIM
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get Tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: NodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4

      - name: npm install build
        run: |
          npm install
          npm run build:prod

      - name: build TAR PACKAGE
        run: |
          cd build
          date >> build-date.log
          tar -czvf glide-im-web.tar.gz *

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          release_name: release_${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: glide-im-web.tar.gz
          asset_name: glide-im-web-${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_content_type: application/gzip

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.UPLOAD_DIR_RELEASE }}
          EXCLUDE: "/dist/, /node_modules/"